### ISSUE TITLE
[FEATURE REQUEST] Create a decorator for config callback

### ISSUE THREAD

**Issue by ezhang7423** [maxb2/typer-config#33]
In the midst of looking at the elegant code for #27  , I noticed a possible simplification for improving the developer experience of this library.  
Instead of the current invocation of 
```
@app.command()
def main(
    arg1: str,
    config: str = typer.Option(
        "",
        callback=yaml_conf_callback,
        is_eager=True,  # THIS IS REALLY IMPORTANT 
    ),
    opt1: str = typer.Option(...),
    opt2: str = typer.Option("hello"),
):
    typer.echo(f"{opt1} {opt2} {arg1}")
```
Could we instead use

```
@app.command()
@use_config(callback=yaml_conf_callback)
def main(
    arg1: str,
    opt1: str = typer.Option(...),
    opt2: str = typer.Option("hello"),
):
    typer.echo(f"{opt1} {opt2} {arg1}")
```
In this case, we could also quite nicely integrate this with #27 through the following:

```
@app.command()
@use_config(callback=yaml_conf_callback, save_location="./saved.yaml")
def main(
    arg1: str,
    opt1: str = typer.Option(...),
    opt2: str = typer.Option("hello"),
):
    typer.echo(f"{opt1} {opt2} {arg1}")
```

**Comment by maxb2** [comment]
I like this idea.

**Comment by maxb2** [comment]
This is actually significantly harder to implement because the `@use_config` decorator needs to change the function signature (add the `config` parameter and its default value). The standard library can't do this. I'm thinking about using this third party library to do it: https://smarie.github.io/python-makefun/api_reference/#wraps. I would prefer not to add more required dependencies. If we do go this route, I would put these in `typer_config.decorators` that doesn't get imported at the top level and contains a check for the optional dependency.

**Comment by ezhang7423** [comment]
Would it be possible to use this?

```python
import functools
import inspect
from inspect import Parameter

def add_argument_decorator(func):
    sig = inspect.signature(func)
    new_params = [
        *sig.parameters.values(),
        Parameter('new_arg', Parameter.KEYWORD_ONLY, default=None),
    ]
    new_sig = sig.replace(parameters=new_params)
    
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        return func(*args, **kwargs)
    
    wrapper.__signature__ = new_sig
    return wrapper

@add_argument_decorator
def test_func(a, b):
    return a + b
```

This decorator adds a new keyword-only argument called new_arg to the decorated function. The inspect.signature function is used to get the function's current signature, and then a new inspect.Parameter is added to the list of parameters.

The wrapper function simply calls the original function, passing along any arguments it receives. Note that in this case, the wrapper doesn't actually do anything with new_arg. If you want the decorator to affect the function's behavior based on new_arg, you would need to add that logic to the wrapper function.

Finally, the decorator replaces the wrapper function's signature with the new signature using wrapper.__signature__ = new_sig. This makes it so that when you inspect the decorated function's signature using inspect.signature, you'll see the modified signature.

Here's an example of how this decorator works:

print(inspect.signature(test_func))  # Returns: (a, b, *, new_arg=None)

**Comment by maxb2** [comment]
I like your solution for using the standard library but it can cause some confusion to the caller (the `typer` library in our case). If you tried to call `test_func(1,2, new_arg=...)` you will get `TypeError: test_func() got an unexpected keyword argument 'new_arg'`. So, I just modified the `kwargs` to match the wrapped function's original signature [here](https://github.com/maxb2/typer-config/blob/feat/decorator-std/typer_config/decorators.py). 

I think this is acceptable for our use case, but should be treated with care. For comparison, [here](https://github.com/maxb2/typer-config/blob/feat/decorator/typer_config/decorators.py) is the third party implementation.
