### ISSUE TITLE
Specify custom config file location with decorators

### ISSUE THREAD

**Issue by johnraz** [maxb2/typer-config#60]
Hello!

I am very happy I found as solution to this "config" support for typer, so first and foremost, thanks for the lib!

Now I think the API of the lib could be improved a bit.
Maybe I missed something, and if that's the case I apologies, but I feel like it would be super nice to have the ability to easily load the config from a custom location.

Right now the only way I found is to override the `config` parameter on each command with something like:
```
    config: Annotated[
        pathlib.Path,
        typer.Option(
            callback=yaml_conf_callback,
            is_eager=True,  # THIS IS REALLY IMPORTANT
        ),
    ] = "/my-custom-path/config.yaml",
```

I feel like it would be a better dev experience if one could do something like:

```
@use_yaml_config(config_location="/my-custom-path/config.yaml")
```

Thanks 🙂

**Comment by maxb2** [comment]
Thanks for the kind words!

I wrote this in a way that is very composable. See the [pyproject.toml example](https://maxb2.github.io/typer-config/1.0.0/examples/pyproject/) for a way to set a default location. 

Adding the `config_location` parameter to the decorator is a good idea though. I'll consider adding that soon.

**Comment by johnraz** [comment]
@maxb2 Thanks a lot, that's what I was looking for 👍 
Maybe it would be nice to gather all the tips and tricks in a dedicated section of the doc?
Like "how do you override the config location" with code example.

**Comment by maxb2** [comment]
That's a great suggestion! I'll add that section to the docs.

FYI, you need to be careful when specifying a default value for `config`. That parameter is processed before any others. So, if it raises an exception on the default value, you can make it so `your-app --help` doesn't work. See [this comment](https://github.com/tiangolo/typer/issues/86#issuecomment-1559115184)

**Comment by maxb2** [comment]
See [1.1.0](https://github.com/maxb2/typer-config/releases/tag/1.1.0) for this feature!

**Comment by johnraz** [comment]
@maxb2  thanks so much for adding it 🥳
