### ISSUE TITLE
Fix incomplete .ini support

### ISSUE THREAD

**Issue by multimeric** [maxb2/typer-config#94]
There seems to be an `ini_loader`, but no `use_ini()`. Also, the help for the `ini_loader` refers to `subpath_loader` which isn't actually in the repo.

**Comment by maxb2** [comment]
Sorry for the late reply.

I didn't make `use_ini()` because you must specify the section in the ini file to load and I couldn't think of a sensible default. Providing `use_ini(section, ...)` makes sense though. I'll add it!

Good catch on the outdated documentation. I'll fix that too.

**Comment by maxb2** [comment]
See [1.2.0](https://github.com/maxb2/typer-config/releases/tag/1.2.0) for this feature!
